## You should change each of the following fields
## to customize your blog

title: Stat 386 Blog
description: "I did some data science. Here's what I found out!" 
author: Spencer Wilson
author_description: "Hi! I'm a guy typing words!" 

url: https://spencer-scw.github.io ## change this to https://yourusername.github.io
baseurl: /386-blog ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  spencer-scw
    twitter: 
    facebook: 
    email: skrewt@byu.edu
    linkedin: 
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




